import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
async function requireOwner(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return null;const {data,error}=await admin.auth.getUser(token);if(error||!data.user)return null;const {data:profile}=await admin.from("rahalati_profiles").select("id,role,status").eq("id",data.user.id).maybeSingle();return profile?.role==="owner"&&profile?.status==="active"?data.user:null}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);const actor=await requireOwner(req);if(!actor)return json({ok:false,error:"UNAUTHORIZED"},401);
 try{const body=await req.json().catch(()=>({})),action=String(body?.action||"");
  if(action==="list"){const {data,error}=await admin.from("rahalati_profiles").select("id,username,email,display_name,role,status,created_at,updated_at").order("created_at",{ascending:true});if(error)throw error;return json({ok:true,users:data||[]})}
  if(action==="create"){const email=String(body?.email||"").trim().toLowerCase(),username=String(body?.username||"").trim().toLowerCase(),displayName=String(body?.display_name||username||"مستخدم").trim().slice(0,80),password=String(body?.password||"");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({ok:false,error:"INVALID_EMAIL"},400);if(!/^[a-z0-9._-]{3,30}$/.test(username))return json({ok:false,error:"INVALID_USERNAME"},400);if(password.length<8||password.length>128)return json({ok:false,error:"INVALID_PASSWORD"},400);const {data:exists}=await admin.from("rahalati_profiles").select("id").or(`email.ilike.${email},username.eq.${username}`).limit(1);if(exists?.length)return json({ok:false,error:"PROFILE_EXISTS"},409);const {data:created,error:createError}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{display_name:displayName}});if(createError||!created.user)return json({ok:false,error:"CREATE_AUTH_FAILED",detail:createError?.message||""},409);const {error:profileError}=await admin.from("rahalati_profiles").insert({id:created.user.id,email,username,display_name:displayName,role:"user",status:"active"});if(profileError){await admin.auth.admin.deleteUser(created.user.id).catch(()=>{});throw profileError}return json({ok:true,user:{id:created.user.id,email,username,display_name:displayName,role:"user",status:"active"}})}
  if(action==="set-status"){const userId=String(body?.user_id||""),status=String(body?.status||"");if(!userId||!["active","disabled"].includes(status))return json({ok:false,error:"INVALID_INPUT"},400);if(userId===actor.id)return json({ok:false,error:"CANNOT_DISABLE_OWNER"},409);const {data:target}=await admin.from("rahalati_profiles").select("role").eq("id",userId).maybeSingle();if(!target||target.role!=="user")return json({ok:false,error:"USER_NOT_FOUND"},404);const {error}=await admin.from("rahalati_profiles").update({status,updated_at:new Date().toISOString()}).eq("id",userId).eq("role","user");if(error)throw error;return json({ok:true,status})}
  if(action==="reset-password"){const userId=String(body?.user_id||""),password=String(body?.password||"");if(!userId||password.length<8||password.length>128)return json({ok:false,error:"INVALID_INPUT"},400);const {data:target}=await admin.from("rahalati_profiles").select("role").eq("id",userId).maybeSingle();if(!target||target.role!=="user")return json({ok:false,error:"USER_NOT_FOUND"},404);const {error}=await admin.auth.admin.updateUserById(userId,{password});if(error)throw error;return json({ok:true})}
  return json({ok:false,error:"UNKNOWN_ACTION"},400)
 }catch(e){console.error("rahalati-admin-users",e instanceof Error?e.message:"unknown");return json({ok:false,error:"SERVER_ERROR"},500)}
});
